"""renamed the table name

Revision ID: 8138467bcd66
Revises: f2397b9c4c22
Create Date: 2022-05-19 21:33:47.103984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8138467bcd66'
down_revision = 'f2397b9c4c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
